[tool.poetry]
name = "marimba"
version = "0.1.0"
description = "Marine Imagery Batch Actions"
authors = [
    "Chris Jackett <chris.jackett@csiro.au>",
    "Kevin Barnard <kbarnard@mbari.org>"
]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.8"
typer = "^0.7.0"
rich = "^13.3.1"
PyYAML = "^6.0"
czifile = "^2019.7.2"
python-dateutil = "^2.8.2"
pandas = "^1.5.3"
cookiecutter = "^2.1.1"
ifdo = "^1.1.0"
pillow = "^9.5.0"
scikit-learn = "^1.2.2"
stitching = "^0.4.0"
opencv-python = "^4.7.0.72"
pyexiv2 = "^2.8.1"
psutil = "^5.9.5"
pydoit = "^0.0.4"
gitpython = "^3.1.40"

[tool.poetry.scripts]
marimba = "marimba.marimba:marimba"

[tool.poetry.group.dev.dependencies]
black = "^23.1.0"
isort = "^5.12.0"
pre-commit = "^3.5.0"
pytest = "^7.4.2"
mkdocs = "^1.5.3"
mkdocstrings = {extras = ["python"], version = "^0.23.0"}
mkdocs-material = "^9.4.6"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.black]
line-length = 150

