---  #Configuration file for nav data
# The following fields will be searched for in nav data files and mapped to corresponding iFDO set-items

ifdo-image-set-items:
  image-datetime: "Date"
  image-latitude: "Latitude"
  image-longitude: "Longitude"
  image-depth: "Depth"
  image-altitude: "Alt"

additional-image-set-items:
  image-sea-water-temperature: "Temperature"
  image-sea-water-salinity: "Salinity"
  image-sea-water-oxygen: "Oxygen"  
